/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package geoesxpofisica;

/**
 *
 * @author aaron
 */
public class Help extends javax.swing.JFrame {

    int xm = 0, ym = 0;
    
    public Help() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contener_p = new javax.swing.JPanel();
        desplazamiento_p = new javax.swing.JPanel();
        Exit = new javax.swing.JButton();
        jPSlider = new javax.swing.JPanel();
        ayuda_tp = new javax.swing.JTabbedPane();
        botones_p = new javax.swing.JPanel();
        consejos_p = new javax.swing.JPanel();
        unidades_p = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1160, 626));
        setResizable(false);
        setSize(new java.awt.Dimension(1160, 626));

        contener_p.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        desplazamiento_p.setBackground(new java.awt.Color(57, 91, 100));
        desplazamiento_p.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                desplazamiento_pMouseDragged(evt);
            }
        });
        desplazamiento_p.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                desplazamiento_pMousePressed(evt);
            }
        });

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Salir-14.png"))); // NOI18N
        Exit.setBorderPainted(false);
        Exit.setContentAreaFilled(false);
        Exit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Salir-15.png"))); // NOI18N
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout desplazamiento_pLayout = new javax.swing.GroupLayout(desplazamiento_p);
        desplazamiento_p.setLayout(desplazamiento_pLayout);
        desplazamiento_pLayout.setHorizontalGroup(
            desplazamiento_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desplazamiento_pLayout.createSequentialGroup()
                .addGap(0, 1125, Short.MAX_VALUE)
                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        desplazamiento_pLayout.setVerticalGroup(
            desplazamiento_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desplazamiento_pLayout.createSequentialGroup()
                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        contener_p.add(desplazamiento_p, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 35));

        jPSlider.setBackground(new java.awt.Color(44, 51, 51));
        jPSlider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPSliderMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPSliderLayout = new javax.swing.GroupLayout(jPSlider);
        jPSlider.setLayout(jPSliderLayout);
        jPSliderLayout.setHorizontalGroup(
            jPSliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        jPSliderLayout.setVerticalGroup(
            jPSliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 591, Short.MAX_VALUE)
        );

        contener_p.add(jPSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 35, 180, 591));

        ayuda_tp.setEnabled(false);

        javax.swing.GroupLayout botones_pLayout = new javax.swing.GroupLayout(botones_p);
        botones_p.setLayout(botones_pLayout);
        botones_pLayout.setHorizontalGroup(
            botones_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
        );
        botones_pLayout.setVerticalGroup(
            botones_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 607, Short.MAX_VALUE)
        );

        ayuda_tp.addTab("Botones", botones_p);

        javax.swing.GroupLayout consejos_pLayout = new javax.swing.GroupLayout(consejos_p);
        consejos_p.setLayout(consejos_pLayout);
        consejos_pLayout.setHorizontalGroup(
            consejos_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
        );
        consejos_pLayout.setVerticalGroup(
            consejos_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 607, Short.MAX_VALUE)
        );

        ayuda_tp.addTab("Consejos", consejos_p);

        javax.swing.GroupLayout unidades_pLayout = new javax.swing.GroupLayout(unidades_p);
        unidades_p.setLayout(unidades_pLayout);
        unidades_pLayout.setHorizontalGroup(
            unidades_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
        );
        unidades_pLayout.setVerticalGroup(
            unidades_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 607, Short.MAX_VALUE)
        );

        ayuda_tp.addTab("Unidades de medidas", unidades_p);

        contener_p.add(ayuda_tp, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, -10, 980, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contener_p, javax.swing.GroupLayout.PREFERRED_SIZE, 1160, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contener_p, javax.swing.GroupLayout.PREFERRED_SIZE, 626, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPSliderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPSliderMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPSliderMouseClicked

    private void desplazamiento_pMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desplazamiento_pMousePressed
        xm = evt.getX();
        ym = evt.getY();
    }//GEN-LAST:event_desplazamiento_pMousePressed

    private void desplazamiento_pMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desplazamiento_pMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xm, y - ym);
    }//GEN-LAST:event_desplazamiento_pMouseDragged

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_ExitActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JTabbedPane ayuda_tp;
    private javax.swing.JPanel botones_p;
    private javax.swing.JPanel consejos_p;
    private javax.swing.JPanel contener_p;
    private javax.swing.JPanel desplazamiento_p;
    private javax.swing.JPanel jPSlider;
    private javax.swing.JPanel unidades_p;
    // End of variables declaration//GEN-END:variables
}
